### ISSUE TITLE
Return `undefined` on equal counts?

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/detect-newline#11]
I noticed the module has a bias towards LF, e.g. when a string contains a equal amount of LF and CRLF, it will return LF. The module's description says it returns the "dominant" variant, but when  they are equal, none dominate and I think it would be more correct to return `undefined`.

**Comment by sindresorhus** [comment]
While you are techincally correct, I think the current behavior is more pragmatic. It would also be too much of a breaking change to change it at this point. It would be better to update the docs to reflect the behavior.

**Comment by silverwind** [comment]
Documenting it only is fine with me.
