### ISSUE TITLE
Return `undefined` when no new lines

### ISSUE THREAD

**Issue by blakeembrey** [sindresorhus/detect-newline#4]
I found a PR that actually did this too, but it was closed as out of scope. (https://github.com/sindresorhus/detect-newline/pull/3)

I think this is actually a common use-case. If there's no newlines, there shouldn't be an newlines returned and the user can use the default. It's on the same bar as https://github.com/sindresorhus/detect-indent, which returns `undefined` as the indent when no indent is detected. This would allow someone to fall back to the OS EOL instead of `\n` when editing an existing file without any new lines.

**Comment by sindresorhus** [comment]
@blakeembrey What's your use-case? I would pretty much use the exact comment as https://github.com/sindresorhus/detect-newline/pull/3#issuecomment-122542911. There's absolutely no reason AFAIK to fall back to `\r\n` if there are no newlines to detect.

**Comment by blakeembrey** [comment]
It comes down to consistency here. When you're creating a new file with OS EOL or none are detected and it starts using `\n`, seems like they should then act the same. Conversation from: https://github.com/typings/typings/issues/81#issuecomment-167113404.

**Comment by sindresorhus** [comment]
Ok, I guess it makes sense when the name is `detect-newline`. I'll do the changes and some other tweaks in the next day.

**Comment by sindresorhus** [comment]
Was fixed by https://github.com/sindresorhus/detect-newline/commit/65aff2dc5c9bdaa2c165cd8230207ae4abbc8239.
