### ISSUE TITLE
`.graceful()` method should return `\n` when given `null`

### ISSUE THREAD

**Issue by MaximDevoir** [sindresorhus/detect-newline#8]
**Current Behavior**

```JavaScript
// This is good/expected
detectNewline(null) // Throws TypeError.

// This is bad/unexpected/not graceful
detectNewline.graceful(null) // Throws TypeError
```

**Expected Behavior**

```
detectNewline.graceful(null) // Return '\n'
```

Expect `graceful` to be gracefully handle `null` input and return `\n`. Package should not throw/crash the app.

**Comment by sindresorhus** [comment]
Yeah, I guess it makes sense to also accept `null` and `undefined`.
